name: Actualizar Portada Organización

env:
  USER_NAME: 'github-actions[bot]'
  USER_EMAIL: 'github-actions[bot]@users.noreply.github.com'

on:
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Ejecutar diariamente a medianoche UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup UV
        uses: astral-sh/setup-uv@v6
        with:
          version: 'latest'
          enable-cache: true
          cache-dependency-glob: .github/pyproject.toml

      - name: Run python script to update profile README
        run: uv run scripts/update_homepage.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.name "${{ env.USER_NAME }}"
          git config --local user.email "${{ env.USER_EMAIL }}"
          git add profile/README.md
          if git diff --staged --quiet; then
            echo "No changes to commit"; exit 0
          else
            git commit -m "docs: update organization profile README [skip ci]"
            git push
          fi
